### ISSUE TITLE
no win32 GUI password prompt

### ISSUE THREAD

**Issue by clach04** [clach04/EncScite#3]
Instead get:

    C:\code\py\EncScite\puren_tonbo>dist\prog\ptcipher.exe --password-prompt=gui --decrypt puren_tonbo\tests\data\aesop.chi
    Traceback (most recent call last):
      File "ptcipher.py", line 189, in <module>
      File "ptcipher.py", line 141, in main
    AttributeError: 'NoneType' object has no attribute 'encode'

pdb will stop (just before call to win32_getpassword() but cannot list code.

**Comment by clach04** [comment]
C:\code\py\EncScite\puren_tonbo>dist\prog\testimport_cli.exe
    Traceback (most recent call last):
      File "testimport_cli.py", line 3, in <module>
        from pywin.mfc import dialog  # pywin32
      File "pywin\mfc\dialog.pyc", line 7, in <module>
      File "win32ui.pyc", line 12, in <module>
      File "win32ui.pyc", line 10, in __load
    ImportError: DLL load failed: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.

> ImportError: DLL load failed: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.

from Event Viewer:

    Activation context generation failed for "C:\code\py\EncScite\puren_tonbo\dist\lib\win32ui.pyd". Dependent Assembly Microsoft.VC90.MFC,processorArchitecture="x86",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.21022.8" could not be found. Please use sxstrace.exe for detailed diagnosis.


> Activation context generation failed for "C:\code\py\EncScite\puren_tonbo\dist\lib\win32ui.pyd". Dependent Assembly Microsoft.VC90.MFC,processorArchitecture="x86",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.21022.8" could not be found. Please use sxstrace.exe for detailed diagnosis.

**Comment by clach04** [comment]
Copying:

    mfc90.dll
    mfc90u.dll
    mfcm90.dll
    mfcm90u.dll

from virtualenv did NOT change behavior at all

**Comment by clach04** [comment]
Nor did copying:

     msvcr90.dll

from python app dir.

**Comment by clach04** [comment]
Cannot see pywin in py2exe lib....

**Comment by clach04** [comment]
Adding pywin to setup.exe include package then fails on pywin.Demos dir, hack workaround,

    delete virtualenv\\Lib\site-packages\pythonwin\pywin\Demo

but still get same error in the event viewer,

**Comment by clach04** [comment]
tried copying  Microsoft.VC90.MFC.manifest, same issue

**Comment by clach04** [comment]
if coming back to this, start with 77fab82545314a07d912061f60cd572e61ec31f4 as a starting point. For now using EasyDialogs.
